services:

  # Redis queue storage used by the scraper jobs.
  redis:
    image: redis:alpine
    container_name: redis
    command: >
      redis-server
      --maxmemory 512mb
      --maxmemory-policy noeviction
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - scraper-network
    deploy:
      resources:
        limits:
          memory: 600m

  # Redis monitoring interface.
  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540"
    networks:
      - scraper-network
    depends_on:
      - redis

  # API service responsible for creating scraper jobs.
  scraper-api:
    build: .
    container_name: scraper-api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - scraper-network
    depends_on:
      - redis

  # Worker service responsible for executing scraping tasks.
  scraper-worker:
    build: .
    container_name: scraper-worker
    tty: true
    command: ["node", "src/runner/JobRunner.js"]
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

      # Runs browser in visible mode.
      - SCRAPER_HEADLESS=false

      # Browser engine used by the scraper.
      - SCRAPER_ENGINE=camoufox

      # Required to run Firefox inside Docker without sandbox issues.
      - MOZ_DISABLE_CONTENT_SANDBOX=1

    # Allows communication with applications running on the host machine.
    extra_hosts:
      - "host.docker.internal:host-gateway"

    # More shared memory for browser processes.
    shm_size: '1gb'

    # Improves browser stability.
    ipc: host

    volumes:
      # Project source code.
      - .:/usr/src/app

      # Keeps container dependencies isolated.
      - /usr/src/app/node_modules

    networks:
      - scraper-network

    depends_on:
      - redis


# Network shared between application services.
networks:
  scraper-network:
    driver: bridge


# Persistent Redis storage.
volumes:
  redis-data: